export const endpoints = [
 ['GET','/auth/me','Current user'],['POST','/auth/register','Register'],['POST','/auth/login','Login'],['GET','/auth/admin-test','Admin authorization test'],['GET','/auth/role-test','Role authorization test'],
 ['GET','/users','List users'],['GET','/users/:id','User detail'],['POST','/users','Create user'],['PATCH','/users/:id','Update user'],
 ['GET','/products','List products'],['GET','/products/:productId','Product detail'],['POST','/products','Create product'],
 ['GET','/products/:productId/batches','List product batches'],['GET','/batches/:batchId','Batch detail'],['POST','/products/:productId/batches','Create batch'],['PATCH','/batches/:batchId','Update batch'],['DELETE','/batches/:batchId','Delete batch'],
 ['GET','/products/:productId/suppliers','Product suppliers'],['POST','/products/:productId/suppliers','Add product supplier'],['PATCH','/products/:productId/suppliers/:supplierId','Update product supplier'],['DELETE','/products/:productId/suppliers/:supplierId','Remove product supplier'],['GET','/suppliers/:supplierId/products','Supplier products'],
 ['GET','/suppliers','List suppliers'],['GET','/suppliers/:id','Supplier detail'],['POST','/suppliers','Create supplier'],['PATCH','/suppliers/:id','Update supplier'],['GET','/suppliers/:supplierId/ledger','Supplier ledger'],
 ['GET','/customers','List customers'],['GET','/customers/:id','Customer detail'],['POST','/customers','Create customer'],['PATCH','/customers/:id','Update customer'],['GET','/customers/:customerId/ledger','Customer ledger'],
 ['GET','/products/:productId/stock','Product stock'],['GET','/batches/:batchId/stock','Batch stock'],['POST','/batches/:batchId/stock','Add stock'],['POST','/batches/:batchId/stock/adjust','Adjust stock'],['POST','/batches/:batchId/stock/reserve','Reserve stock'],['POST','/batches/:batchId/stock/release','Release stock'],['GET','/products/:productId/stock/movements','Product movements'],['GET','/batches/:batchId/stock/movements','Batch movements'],['POST','/batches/:batchId/stock/sell','Sell stock'],['POST','/batches/:batchId/stock/sales-return','Stock sales return'],['POST','/batches/:batchId/stock/purchase-return','Stock purchase return'],['POST','/batches/:batchId/stock/damage','Damage stock'],['POST','/batches/:batchId/stock/confirm-sale','Confirm sale'],['POST','/batches/:batchId/stock/expire','Expire stock'],['POST','/batches/:batchId/stock/transfer','Transfer stock'],
 ['POST','/purchases','Create purchase'],['GET','/purchases','List purchases'],['GET','/purchases/:purchaseId','Purchase detail'],['POST','/purchases/:purchaseId/return','Purchase return'],['POST','/purchases/:purchaseId/payments','Purchase payment'],['GET','/purchases/:purchaseId/payments','Purchase payments'],
 ['POST','/sales','Create sale'],['GET','/sales','List sales'],['GET','/sales/:id','Sale detail'],['POST','/sales/:saleId/payments','Sale payment'],['GET','/sales/:saleId/payments','Sale payments'],['POST','/sales/:saleId/return','Sales return'],
 ['GET','/dashboard','Dashboard'],
 ['GET','/health','API health']
];
