import React from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import api, { apiError, unwrap } from '../lib/api';
import { Badge, Button, Card, Input, Select, Table, date, money } from '../components/ui';

const blank = { batchNumber: '', manufacturingDate: '', expiryDate: '', purchasePrice: '', costPerBaseUnit: '', mrp: '', sellingPrice: '', status: 'ACTIVE' };

export default function Batches() {
  const qc = useQueryClient();
  const [productId, setProductId] = React.useState('');
  const [editing, setEditing] = React.useState(null);
  const [form, setForm] = React.useState(blank);
  const products = useQuery({ queryKey: ['products'], queryFn: async () => unwrap(await api.get('/products')) });
  const batches = useQuery({ queryKey: ['batches', productId], enabled: !!productId, queryFn: async () => unwrap(await api.get(`/products/${productId}/batches`)) });
  const save = useMutation({ mutationFn: data => editing ? api.patch(`/batches/${editing.id}`, data) : api.post(`/products/${productId}/batches`, data), onSuccess: () => { qc.invalidateQueries({ queryKey: ['batches', productId] }); setEditing(null); setForm(blank); } });
  const remove = useMutation({ mutationFn: id => api.delete(`/batches/${id}`), onSuccess: () => qc.invalidateQueries({ queryKey: ['batches', productId] }) });
  const update = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const submit = event => { event.preventDefault(); save.mutate({ ...form, purchasePrice: Number(form.purchasePrice), costPerBaseUnit: Number(form.costPerBaseUnit || 0), mrp: Number(form.mrp), sellingPrice: Number(form.sellingPrice) }); };
  const edit = batch => { setEditing(batch); setForm({ ...blank, ...batch, manufacturingDate: batch.manufacturingDate?.slice(0, 10) || '', expiryDate: batch.expiryDate?.slice(0, 10) || '' }); };
  return <div><div className="pageIntro"><div><span className="eyebrow">Catalog</span><h2>Product batches</h2><p className="muted">Track pricing, expiry and status at batch level.</p></div></div><Card title="Choose product"><Select label="Product" value={productId} onChange={event => { setProductId(event.target.value); setEditing(null); }}><option value="">Select a product</option>{(products.data || []).map(product => <option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</Select></Card>{productId && <><Card title={editing ? 'Edit batch' : 'Create batch'}><form className="formGrid" onSubmit={submit}>{[['batchNumber','Batch number','text'],['manufacturingDate','Manufactured','date'],['expiryDate','Expiry date','date'],['purchasePrice','Purchase price','number'],['costPerBaseUnit','Cost per base unit','number'],['mrp','MRP','number'],['sellingPrice','Selling price','number']].map(([key, label, type]) => <Input key={key} label={label} type={type} step="0.01" value={form[key]} onChange={event => update(key, event.target.value)} required={['batchNumber', 'expiryDate', 'mrp', 'sellingPrice'].includes(key)} />)}<Select label="Status" value={form.status} onChange={event => update('status', event.target.value)}><option>ACTIVE</option><option>INACTIVE</option><option>EXPIRED</option></Select><div className="formActions"><Button disabled={save.isPending}>{save.isPending ? 'Saving...' : editing ? 'Save changes' : 'Create batch'}</Button>{editing && <Button type="button" variant="ghost" onClick={() => { setEditing(null); setForm(blank); }}>Cancel</Button>}</div></form>{save.isError && <div className="alert errorBox">{apiError(save.error)}</div>}</Card><Card title={`${(batches.data || []).length} batches`}><Table columns={[{ key: 'batchNumber', label: 'Batch' }, { key: 'manufacturingDate', label: 'Manufactured', render: row => date(row.manufacturingDate) || '-' }, { key: 'expiryDate', label: 'Expiry', render: row => date(row.expiryDate) }, { key: 'purchasePrice', label: 'Purchase', render: row => money(row.purchasePrice) }, { key: 'mrp', label: 'MRP', render: row => money(row.mrp) }, { key: 'sellingPrice', label: 'Selling', render: row => money(row.sellingPrice) }, { key: 'status', label: 'Status', render: row => <Badge tone={row.status === 'ACTIVE' ? 'success' : 'warning'}>{row.status}</Badge> }, { key: 'actions', label: 'Actions', render: row => <span className="tableActions"><Button variant="ghost" onClick={() => edit(row)}>Edit</Button><Button variant="danger" onClick={() => remove.mutate(row.id)}>Delete</Button></span> }]} rows={batches.data || []} /></Card></>}</div>;
}