import React from 'react';
import { useQuery } from '@tanstack/react-query';
import api, { apiError, unwrap } from '../lib/api';
import { ArrowDownLeft, ArrowUpRight, BookOpen, CalendarDays, CreditCard, FileText, Wallet } from 'lucide-react';
import { Badge, Button, Card, Table, date, money } from '../components/ui';

export default function Ledgers({ type }) {
  const isCustomer = type === 'customer';
  const [id, setId] = React.useState('');
  const list = useQuery({ queryKey: [`${type}-ledger-list`], queryFn: async () => unwrap(await api.get(isCustomer ? '/customers' : '/suppliers')) });
  const ledger = useQuery({ queryKey: [type, 'ledger', id], enabled: !!id, queryFn: async () => unwrap(await api.get(isCustomer ? `/customers/${id}/ledger` : `/suppliers/${id}/ledger`)) });
  const account = ledger.data?.[isCustomer ? 'customer' : 'supplier'];
  const entries = ledger.data?.entries || [];
  const summary = ledger.data?.summary || {};
  return <div><div className="pageIntro"><div><span className="eyebrow">Finance</span><h2>{isCustomer ? 'Customer' : 'Supplier'} ledger</h2><p className="muted">Review account activity, balances and transaction history.</p></div><Badge tone="success"><BookOpen size={13} /> Live ledger</Badge></div><Card title="Select account"><div className="ledgerSelector"><label className="field"><span>{isCustomer ? 'Customer' : 'Supplier'}</span><select value={id} onChange={event => setId(event.target.value)}><option value="">Choose an account</option>{(list.data || []).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Button onClick={() => ledger.refetch()} disabled={!id || ledger.isFetching}>{ledger.isFetching ? 'Loading...' : 'View ledger'}</Button></div>{list.isError && <div className="alert errorBox">{apiError(list.error)}</div>}</Card>{ledger.isError && <div className="alert errorBox">{apiError(ledger.error)}</div>}{ledger.isLoading && <div className="loading">Loading account ledger...</div>}{account && <><div className="ledgerAccount"><div className="accountIcon"><Wallet size={20} /></div><div><span className="eyebrow">Account overview</span><h3>{account.name}</h3><p className="muted">Opening balance: {money(account.openingBalance)}</p></div><div className="accountBalance"><span>Current balance</span><strong>{money(summary.balance)}</strong><Badge tone={summary.balance > 0 ? 'warning' : 'success'}>{summary.balance > 0 ? 'Outstanding' : 'Clear'}</Badge></div></div><div className="ledgerKpis"><LedgerKpi icon={ArrowUpRight} label="Total debit" value={summary.totalDebit} tone="debit" /><LedgerKpi icon={ArrowDownLeft} label="Total credit" value={summary.totalCredit} tone="credit" /><LedgerKpi icon={CreditCard} label="Transactions" value={entries.length} tone="count" numeric /></div><Card title="Transaction history" actions={<span className="muted ledgerCount"><FileText size={14} /> {entries.length} entries</span>}><Table columns={[{ key: 'entryDate', label: 'Date', render: row => <span className="dateCell"><CalendarDays size={14} />{date(row.entryDate)}</span> }, { key: 'entryType', label: 'Type', render: row => <Badge tone={row.debit > 0 ? 'warning' : 'success'}>{String(row.entryType || 'ENTRY').replaceAll('_', ' ')}</Badge> }, { key: 'description', label: 'Description', render: row => <div><strong>{row.description || 'Ledger entry'}</strong>{row.referenceNumber && <small className="reference">Ref: {row.referenceNumber}</small>}</div> }, { key: 'debit', label: 'Debit', render: row => <span className="amount debit">{row.debit ? money(row.debit) : '-'}</span> }, { key: 'credit', label: 'Credit', render: row => <span className="amount credit">{row.credit ? money(row.credit) : '-'}</span> }, { key: 'balance', label: 'Running balance', render: row => <strong>{money(row.balance)}</strong> }]} rows={[...entries].reverse()} /></Card></>}</div>;
}

function LedgerKpi({ icon: Icon, label, value, tone, numeric }) { return <div className={`ledgerKpi ${tone}`}><div className="ledgerKpiIcon"><Icon size={17} /></div><div><span>{label}</span><strong>{numeric ? value : money(value)}</strong></div></div>; }
