import React from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import api, { apiError, unwrap } from '../lib/api';
import { Badge, Button, Card, Input, Select, Table, money } from '../components/ui';

export default function ProductSuppliers() {
  const qc = useQueryClient();
  const [productId, setProductId] = React.useState('');
  const [form, setForm] = React.useState({ supplierId: '', supplierProductCode: '', purchasePrice: '', creditDays: '', isPreferred: false });
  const products = useQuery({ queryKey: ['products'], queryFn: async () => unwrap(await api.get('/products')) });
  const suppliers = useQuery({ queryKey: ['suppliers'], queryFn: async () => unwrap(await api.get('/suppliers')) });
  const linked = useQuery({ queryKey: ['product-suppliers', productId], enabled: !!productId, queryFn: async () => unwrap(await api.get(`/products/${productId}/suppliers`)) });
  const add = useMutation({ mutationFn: data => api.post(`/products/${productId}/suppliers`, data), onSuccess: () => { qc.invalidateQueries({ queryKey: ['product-suppliers', productId] }); setForm({ supplierId: '', supplierProductCode: '', purchasePrice: '', creditDays: '', isPreferred: false }); } });
  const remove = useMutation({ mutationFn: supplierId => api.delete(`/products/${productId}/suppliers/${supplierId}`), onSuccess: () => qc.invalidateQueries({ queryKey: ['product-suppliers', productId] }) });
  const submit = event => { event.preventDefault(); add.mutate({ ...form, purchasePrice: Number(form.purchasePrice), creditDays: Number(form.creditDays || 0) }); };
  return <div><div className="pageIntro"><div><span className="eyebrow">Catalog</span><h2>Product suppliers</h2><p className="muted">Link approved suppliers, costs and preferred sourcing.</p></div></div><Card title="Choose product"><Select label="Product" value={productId} onChange={event => setProductId(event.target.value)}><option value="">Select a product</option>{(products.data || []).map(product => <option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</Select></Card>{productId && <><Card title="Link supplier"><form className="formGrid" onSubmit={submit}><Select label="Supplier" value={form.supplierId} onChange={event => setForm({ ...form, supplierId: event.target.value })} required><option value="">Select supplier</option>{(suppliers.data || []).map(supplier => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</Select><Input label="Supplier product code" value={form.supplierProductCode} onChange={event => setForm({ ...form, supplierProductCode: event.target.value })} /><Input label="Purchase price" type="number" step="0.01" value={form.purchasePrice} onChange={event => setForm({ ...form, purchasePrice: event.target.value })} required /><Input label="Credit days" type="number" value={form.creditDays} onChange={event => setForm({ ...form, creditDays: event.target.value })} /><label className="check"><input type="checkbox" checked={form.isPreferred} onChange={event => setForm({ ...form, isPreferred: event.target.checked })} /> Preferred supplier</label><div className="formActions"><Button disabled={add.isPending}>{add.isPending ? 'Linking...' : 'Link supplier'}</Button></div></form>{add.isError && <div className="alert errorBox">{apiError(add.error)}</div>}</Card><Card title="Linked suppliers"><Table columns={[{ key: 'supplier', label: 'Supplier', render: row => row.supplier?.name || row.name || '-' }, { key: 'supplierProductCode', label: 'Supplier code' }, { key: 'purchasePrice', label: 'Purchase price', render: row => money(row.purchasePrice) }, { key: 'creditDays', label: 'Credit days' }, { key: 'isPreferred', label: 'Preferred', render: row => <Badge tone={row.isPreferred ? 'success' : 'neutral'}>{row.isPreferred ? 'Yes' : 'No'}</Badge> }, { key: 'actions', label: 'Actions', render: row => <Button variant="danger" onClick={() => remove.mutate(row.supplierId || row.supplier?.id)}>Remove</Button> }]} rows={linked.data || []} /></Card></>}</div>;
}