import React from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import api, { unwrap, apiError } from '../lib/api';
import { Card, Table, Button, Input, Select, Badge, money, date } from '../components/ui';

const fields = [['name', 'Name'], ['contactPerson', 'Contact person'], ['phone', 'Phone'], ['alternatePhone', 'Alternate phone'], ['email', 'Email'], ['gstin', 'GSTIN'], ['drugLicenseNo', 'Drug licence'], ['address', 'Address'], ['city', 'City'], ['state', 'State'], ['pincode', 'Pincode'], ['creditLimit', 'Credit limit'], ['creditDays', 'Credit days'], ['openingBalance', 'Opening balance']];

export default function Suppliers() {
  const qc = useQueryClient();
  const [selected, setSelected] = React.useState(null);
  const [edit, setEdit] = React.useState(null);
  const [show, setShow] = React.useState(false);
  const blank = Object.fromEntries(fields.map(([key]) => [key, '']));
  const [form, setForm] = React.useState(blank);
  const query = useQuery({ queryKey: ['suppliers'], queryFn: async () => unwrap(await api.get('/suppliers')) });
  const save = useMutation({ mutationFn: data => edit ? api.patch(`/suppliers/${edit.id}`, data) : api.post('/suppliers', data), onSuccess: () => { qc.invalidateQueries({ queryKey: ['suppliers'] }); setShow(false); setEdit(null); } });
  const openEdit = supplier => { setEdit(supplier); setForm(Object.fromEntries(fields.map(([key]) => [key, supplier[key] ?? '']))); setShow(true); };
  const submit = event => { event.preventDefault(); save.mutate({ ...form, creditLimit: Number(form.creditLimit || 0), creditDays: Number(form.creditDays || 0), openingBalance: Number(form.openingBalance || 0), status: form.status || edit?.status || 'ACTIVE' }); };
  return <div><div className="pageIntro"><div><span className="eyebrow">Master data</span><h2>Suppliers</h2><p className="muted">Supplier master, credit terms and ledger access.</p></div><Button onClick={() => { setEdit(null); setForm(blank); setShow(!show); }}>+ New supplier</Button></div>{show && <Card title={edit ? 'Edit supplier' : 'Create supplier'}><form className="formGrid" onSubmit={submit}>{fields.map(([key, label]) => <Input key={key} label={label} value={form[key]} onChange={event => setForm({ ...form, [key]: event.target.value })} />)}<Select label="Status" value={form.status || edit?.status || 'ACTIVE'} onChange={event => setForm({ ...form, status: event.target.value })}><option>ACTIVE</option><option>INACTIVE</option><option>BLOCKED</option></Select><div className="formActions"><Button disabled={save.isPending}>{save.isPending ? 'Saving...' : edit ? 'Save changes' : 'Create supplier'}</Button><Button type="button" variant="ghost" onClick={() => setShow(false)}>Cancel</Button></div></form>{save.isError && <div className="alert errorBox">{apiError(save.error)}</div>}</Card>}<Card title="Supplier directory"><Table onRow={setSelected} columns={[{ key: 'name', label: 'Supplier' }, { key: 'contactPerson', label: 'Contact' }, { key: 'phone', label: 'Phone' }, { key: 'gstin', label: 'GSTIN' }, { key: 'creditLimit', label: 'Credit limit', render: row => money(row.creditLimit) }, { key: 'status', label: 'Status', render: row => <Badge tone={row.status === 'ACTIVE' ? 'success' : 'warning'}>{row.status || 'ACTIVE'}</Badge> }, { key: 'actions', label: 'Actions', render: row => <span className="tableActions"><Button variant="ghost" onClick={event => { event.stopPropagation(); openEdit(row); }}>Edit</Button><Button variant="ghost" onClick={event => { event.stopPropagation(); setSelected(row); }}>View</Button></span> }]} rows={query.data || []} /></Card>{selected && <SupplierDetail supplier={selected} close={() => setSelected(null)} />}</div>;
}

function SupplierDetail({ supplier, close }) {
  const detail = useQuery({ queryKey: ['supplier', supplier.id], queryFn: async () => unwrap(await api.get(`/suppliers/${supplier.id}`)) });
  const products = useQuery({ queryKey: ['supplier-products', supplier.id], queryFn: async () => unwrap(await api.get(`/suppliers/${supplier.id}/products`)) });
  const ledger = useQuery({ queryKey: ['supplier-ledger', supplier.id], queryFn: async () => unwrap(await api.get(`/suppliers/${supplier.id}/ledger`)) });
  const record = detail.data || supplier;
  const entries = ledger.data?.entries || [];
  return <div className="drawerBackdrop" onClick={close}><aside className="drawer" onClick={event => event.stopPropagation()}><div className="drawerHead"><div><span className="eyebrow">Supplier profile</span><h2>{record.name}</h2><p className="muted">{record.status || 'ACTIVE'} supplier account</p></div><button className="iconBtn" onClick={close}>×</button></div><div className="detailGrid"><div><span>Contact</span><b>{record.contactPerson || '-'}</b></div><div><span>Phone</span><b>{record.phone || '-'}</b></div><div><span>Email</span><b>{record.email || '-'}</b></div><div><span>GSTIN</span><b>{record.gstin || '-'}</b></div><div><span>Credit limit</span><b>{money(record.creditLimit)}</b></div><div><span>Credit days</span><b>{record.creditDays || 0}</b></div></div><Card title="Linked products"><Table columns={[{ key: 'product', label: 'Product', render: row => row.product?.name || row.name || '-' }, { key: 'purchasePrice', label: 'Purchase', render: row => money(row.purchasePrice) }, { key: 'isPreferred', label: 'Preferred', render: row => row.isPreferred ? 'Yes' : 'No' }]} rows={products.data || []} /></Card><Card title="Ledger summary"><div className="detailGrid"><div><span>Total debit</span><b>{money(ledger.data?.summary?.totalDebit)}</b></div><div><span>Total credit</span><b>{money(ledger.data?.summary?.totalCredit)}</b></div><div><span>Balance</span><b>{money(ledger.data?.summary?.balance)}</b></div></div><Table columns={[{ key: 'entryDate', label: 'Date', render: row => date(row.entryDate) }, { key: 'description', label: 'Description' }, { key: 'debit', label: 'Debit', render: row => money(row.debit) }, { key: 'credit', label: 'Credit', render: row => money(row.credit) }]} rows={entries.slice(-8).reverse()} /></Card></aside></div>;
}
